#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x860B7FBB32F8119D (simon@yubico.com)
#
Name     : compat-libidn-soname11
Version  : 1.33
Release  : 5
URL      : http://mirrors.kernel.org/gnu/libidn/libidn-1.33.tar.gz
Source0  : http://mirrors.kernel.org/gnu/libidn/libidn-1.33.tar.gz
Source1 : http://mirrors.kernel.org/gnu/libidn/libidn-1.33.tar.gz.sig
Summary  : IETF stringprep, nameprep, punycode, IDNA text processing.
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT
Requires: compat-libidn-soname11-lib = %{version}-%{release}
Requires: compat-libidn-soname11-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : emacs
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : valgrind
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
See the end for copying conditions.
Libidn is a package for internationalized string handling based on the
Stringprep, Punycode, IDNA and TLD specifications.  Libidn is a GNU
project.  See the file COPYING for licensing information.

%package lib
Summary: lib components for the compat-libidn-soname11 package.
Group: Libraries
Requires: compat-libidn-soname11-license = %{version}-%{release}

%description lib
lib components for the compat-libidn-soname11 package.


%package lib32
Summary: lib32 components for the compat-libidn-soname11 package.
Group: Default
Requires: compat-libidn-soname11-license = %{version}-%{release}

%description lib32
lib32 components for the compat-libidn-soname11 package.


%package license
Summary: license components for the compat-libidn-soname11 package.
Group: Default

%description license
license components for the compat-libidn-soname11 package.


%prep
%setup -q -n libidn-1.33
pushd ..
cp -a libidn-1.33 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567813360
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1567813360
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libidn-soname11
cp COPYING %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/COPYING
cp COPYING.LESSERv2 %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/COPYING.LESSERv2
cp COPYING.LESSERv3 %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/COPYING.LESSERv3
cp COPYINGv2 %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/COPYINGv2
cp COPYINGv3 %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/COPYINGv3
cp doc/specifications/COPYING.UCD %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/doc_specifications_COPYING.UCD
cp java/LICENSE-2.0.txt %{buildroot}/usr/share/package-licenses/compat-libidn-soname11/java_LICENSE-2.0.txt
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/idn
rm -f %{buildroot}/usr/include/idn-free.h
rm -f %{buildroot}/usr/include/idn-int.h
rm -f %{buildroot}/usr/include/idna.h
rm -f %{buildroot}/usr/include/pr29.h
rm -f %{buildroot}/usr/include/punycode.h
rm -f %{buildroot}/usr/include/stringprep.h
rm -f %{buildroot}/usr/include/tld.h
rm -f %{buildroot}/usr/lib32/libidn.so
rm -f %{buildroot}/usr/lib32/pkgconfig/32libidn.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libidn.pc
rm -f %{buildroot}/usr/lib64/libidn.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libidn.pc
rm -f %{buildroot}/usr/share/emacs/site-lisp/idna.el
rm -f %{buildroot}/usr/share/emacs/site-lisp/punycode.el
rm -f %{buildroot}/usr/share/info/libidn-components.png
rm -f %{buildroot}/usr/share/info/libidn.info
rm -f %{buildroot}/usr/share/man/man1/idn.1
rm -f %{buildroot}/usr/share/man/man3/idn_free.3
rm -f %{buildroot}/usr/share/man/man3/idna_strerror.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_ascii_4i.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_ascii_4z.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_ascii_8z.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_ascii_lz.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_44i.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_4z4z.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_8z4z.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_8z8z.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_8zlz.3
rm -f %{buildroot}/usr/share/man/man3/idna_to_unicode_lzlz.3
rm -f %{buildroot}/usr/share/man/man3/pr29_4.3
rm -f %{buildroot}/usr/share/man/man3/pr29_4z.3
rm -f %{buildroot}/usr/share/man/man3/pr29_8z.3
rm -f %{buildroot}/usr/share/man/man3/pr29_strerror.3
rm -f %{buildroot}/usr/share/man/man3/punycode_decode.3
rm -f %{buildroot}/usr/share/man/man3/punycode_encode.3
rm -f %{buildroot}/usr/share/man/man3/punycode_strerror.3
rm -f %{buildroot}/usr/share/man/man3/stringprep.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_4i.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_4zi.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_check_version.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_convert.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_locale_charset.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_locale_to_utf8.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_profile.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_strerror.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_ucs4_nfkc_normalize.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_ucs4_to_utf8.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_unichar_to_utf8.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_utf8_nfkc_normalize.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_utf8_to_locale.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_utf8_to_ucs4.3
rm -f %{buildroot}/usr/share/man/man3/stringprep_utf8_to_unichar.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_4.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_4t.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_4tz.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_4z.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_8z.3
rm -f %{buildroot}/usr/share/man/man3/tld_check_lz.3
rm -f %{buildroot}/usr/share/man/man3/tld_default_table.3
rm -f %{buildroot}/usr/share/man/man3/tld_get_4.3
rm -f %{buildroot}/usr/share/man/man3/tld_get_4z.3
rm -f %{buildroot}/usr/share/man/man3/tld_get_table.3
rm -f %{buildroot}/usr/share/man/man3/tld_get_z.3
rm -f %{buildroot}/usr/share/man/man3/tld_strerror.3
## install_append content
rm -rf %{buildroot}/usr/share/locale
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libidn.so.11
/usr/lib64/libidn.so.11.6.16

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libidn.so.11
/usr/lib32/libidn.so.11.6.16

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libidn-soname11/COPYING
/usr/share/package-licenses/compat-libidn-soname11/COPYING.LESSERv2
/usr/share/package-licenses/compat-libidn-soname11/COPYING.LESSERv3
/usr/share/package-licenses/compat-libidn-soname11/COPYINGv2
/usr/share/package-licenses/compat-libidn-soname11/COPYINGv3
/usr/share/package-licenses/compat-libidn-soname11/doc_specifications_COPYING.UCD
/usr/share/package-licenses/compat-libidn-soname11/java_LICENSE-2.0.txt
